Repository codestates-seb/seb43_main_028, pull requests merged in 2023-05, with the labels that each got.

#4 Chore: 백엔드 기본환경 설정 (#3)
  server/.gitignore
  server/README.md
  server/build.gradle
  server/gradle/wrapper/gradle-wrapper.jar
  server/gradle/wrapper/gradle-wrapper.properties
  server/gradlew
  server/gradlew.bat
  server/settings.gradle
  server/src/main/java/backend/section6mainproject/Section6MainProjectApplication.java
  server/src/main/resources/application.properties
  server/src/test/java/backend/section6mainproject/Section6MainProjectApplicationTests.java
Labels: 김승철, 설정

#6 Feat: 엔티티 클래스 생성, Audit기능 구현 (#5)
  server/build.gradle
  server/src/main/java/backend/section6mainproject/Section6MainProjectApplication.java
  server/src/main/java/backend/section6mainproject/audit/Auditable.java
  server/src/main/java/backend/section6mainproject/content/entity/WalkLogContent.java
  server/src/main/java/backend/section6mainproject/content/repository/ContentRepository.java
  server/src/main/java/backend/section6mainproject/coordinate/entity/Coordinate.java
  server/src/main/java/backend/section6mainproject/coordinate/repository/CoordinateRepository.java
  server/src/main/java/backend/section6mainproject/member/entity/Member.java
  server/src/main/java/backend/section6mainproject/member/repository/MemberRepository.java
  server/src/main/java/backend/section6mainproject/walklog/entity/WalkLog.java
  server/src/main/java/backend/section6mainproject/walklog/repository/WalkLogRepository.java
  server/src/main/resources/application.properties
  server/src/main/resources/application.yml
Labels: 김승철, 기능

#12 [FE] Chore: 개발환경 설정 (#11)
  client/.eslintignore
  client/.eslintrc.cjs
  client/.gitignore
  client/.prettierrc
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/main.tsx
  client/src/vite-env.d.ts
  client/tsconfig.json
  client/tsconfig.node.json
  client/vite.config.ts
Labels: 허상범, 하종승, 박설화, 설정

#14 [FE] Feat: PWA 적용 & Vercel 자동배포 설정 (#13)
  client/.eslintignore
  client/index.html
  client/public/icons/logo-512.png
  client/public/manifest.json
  client/public/sw.js
Labels: 허상범, 하종승, 박설화, 기능, 설정

#17 Feat: WalkLog post 기능 구현 및 테스트 작성 (#7)
  server/src/main/java/backend/section6mainproject/member/repository/MemberRepository.java
  server/src/main/java/backend/section6mainproject/member/service/MemberService.java
  server/src/main/java/backend/section6mainproject/walklog/controller/WalkLogController.java
  server/src/main/java/backend/section6mainproject/walklog/dto/WalkLogDto.java
  server/src/main/java/backend/section6mainproject/walklog/mapper/WalkLogMapper.java
  server/src/main/java/backend/section6mainproject/walklog/service/WalkLogService.java
  server/src/test/java/backend/section6mainproject/walklog/controller/WalkLogControllerTest.java
  server/src/test/java/backend/section6mainproject/walklog/service/WalkLogServiceTest.java
Labels: 김성수, 기능

#20 [FE] Feat: SCSS 모듈 적용, 전역 스타일링 설정 #19
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/styles/_reset.scss
  client/src/styles/global.scss
  client/tsconfig.json
Labels: 허상범, 하종승, 박설화, 기능, 설정

#22 [FE] 기본 라우터 설정 & 폴더 구조 잡기 #21
  client/src/App.tsx
  client/src/apis/index.ts
  client/src/assets/index.ts
  client/src/components/AfterWalk/index.ts
  client/src/components/Feed/index.ts
  client/src/components/HistoryDetail/index.ts
  client/src/components/HistoryList/index.ts
  client/src/components/Home/index.ts
  client/src/components/MyPage/index.ts
  client/src/components/NotFound/index.ts
  client/src/components/OnWalk/index.ts
  client/src/components/SignIn/index.ts
  client/src/components/SignUp/index.ts
  client/src/components/common/index.ts
  client/src/hooks/index.ts
  client/src/main.tsx
  client/src/pages/AfterWalk.tsx
  client/src/pages/Feed.tsx
  client/src/pages/HistoryDetail.tsx
  client/src/pages/HistoryList.tsx
  client/src/pages/Home.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/NotFound.tsx
  client/src/pages/OnWalk.tsx
  client/src/pages/SignIn.tsx
  client/src/pages/SignUp.tsx
  client/src/pages/index.ts
  client/src/router/index.tsx
  client/src/utils/index.ts
Labels: 허상범, 하종승, 박설화, 기능

#25 Feat: WalkLog petch 기능 구현 및 테스트 작성 (#18)
  server/src/main/java/backend/section6mainproject/member/controller/MemberController.java
  server/src/main/java/backend/section6mainproject/member/mapper/MemberMapper.java
  server/src/main/java/backend/section6mainproject/member/service/MemberService.java
  server/src/main/java/backend/section6mainproject/walklog/controller/WalkLogController.java
  server/src/main/java/backend/section6mainproject/walklog/dto/WalkLogDto.java
  server/src/main/java/backend/section6mainproject/walklog/entity/WalkLog.java
  server/src/main/java/backend/section6mainproject/walklog/mapper/WalkLogMapper.java
  server/src/main/java/backend/section6mainproject/walklog/service/WalkLogService.java
  server/src/test/java/backend/section6mainproject/walklog/controller/WalkLogControllerTest.java
  server/src/test/java/backend/section6mainproject/walklog/service/WalkLogServiceTest.java
Labels: 김성수, 기능

#23 Feat: 웹소켓을 이용한 좌표 전송 기능 구현 (#9)
  server/build.gradle
  server/src/main/java/backend/section6mainproject/coordinate/WebSocketBrokerConfig.java
  server/src/main/java/backend/section6mainproject/coordinate/controller/CoordinateController.java
  server/src/main/java/backend/section6mainproject/coordinate/dto/CoordinateDTO.java
  server/src/main/java/backend/section6mainproject/coordinate/interceptor/ConnectionInterceptor.java
  server/src/main/java/backend/section6mainproject/coordinate/interceptor/SubscribeInterceptor.java
  server/src/main/java/backend/section6mainproject/coordinate/mapper/CoordinateMapper.java
  server/src/main/java/backend/section6mainproject/coordinate/service/CoordinateService.java
  server/src/main/java/backend/section6mainproject/coordinate/service/CoordinateServiceImpl.java
  server/src/main/java/backend/section6mainproject/member/service/MemberService.java
  server/src/main/java/backend/section6mainproject/walklog/controller/WalkLogController.java
Labels: 김승철, 기능

#30 18 be feat walklog get기능 구현
  server/src/main/java/backend/section6mainproject/walklog/controller/WalkLogController.java
  server/src/main/java/backend/section6mainproject/walklog/dto/WalkLogDTO.java
  server/src/main/java/backend/section6mainproject/walklog/mapper/WalkLogMapper.java
  server/src/main/java/backend/section6mainproject/walklog/service/WalkLogService.java
  server/src/main/java/backend/section6mainproject/walklog/service/WalkLogServiceImpl.java
  server/src/test/java/backend/section6mainproject/walklog/controller/WalkLogControllerTest.java
  server/src/test/java/backend/section6mainproject/walklog/service/WalkLogServiceImplTest.java
Labels: 김성수, 기능

#32 Feat: @NotSpace 어노테이션 기능추가 (#29)
  server/src/main/java/backend/section6mainproject/member/dto/MemberDto.java
  server/src/main/java/backend/section6mainproject/validator/NotSpace.java
  server/src/main/java/backend/section6mainproject/validator/NotSpaceValidator.java
Labels: 이재환, 기능

#34 Feat: Member Patch (#33)
  server/src/main/java/backend/section6mainproject/coordinate/WebSocketBrokerConfig.java
  server/src/main/java/backend/section6mainproject/coordinate/interceptor/ConnectionInterceptor.java
  server/src/main/java/backend/section6mainproject/member/controller/MemberController.java
  server/src/main/java/backend/section6mainproject/member/dto/MemberDTO.java
  server/src/main/java/backend/section6mainproject/member/mapper/MemberMapper.java
  server/src/main/java/backend/section6mainproject/member/service/MemberService.java
  server/src/main/java/backend/section6mainproject/member/service/MemberServiceImpl.java
  server/src/main/java/backend/section6mainproject/utils/CustomBeanUtils.java
  server/src/main/java/backend/section6mainproject/walklog/service/WalkLogServiceImpl.java
  server/src/test/java/backend/section6mainproject/walklog/service/WalkLogServiceImplTest.java
Labels: 이재환, 기능

#38 28 be feat 걷기 중 사진이나 텍스트를 업로드 하는 기능 구현
  server/build.gradle
  server/src/main/java/backend/section6mainproject/content/controller/WalkLogContentController.java
  server/src/main/java/backend/section6mainproject/content/dto/WalkLogContentDTO.java
  server/src/main/java/backend/section6mainproject/content/entity/WalkLogContent.java
  server/src/main/java/backend/section6mainproject/content/mapper/WalkLogContentMapper.java
  server/src/main/java/backend/section6mainproject/content/repository/WalkLogContentRepository.java
  server/src/main/java/backend/section6mainproject/content/service/AWSS3StorageService.java
  server/src/main/java/backend/section6mainproject/content/service/StorageService.java
  server/src/main/java/backend/section6mainproject/content/service/WalkLogContentService.java
  server/src/main/java/backend/section6mainproject/content/service/WalkLogContentServiceImpl.java
  server/src/main/java/backend/section6mainproject/utils/CustomBeanUtils.java
  server/src/main/java/backend/section6mainproject/walklog/dto/WalkLogDTO.java
  server/src/main/java/backend/section6mainproject/walklog/mapper/WalkLogMapper.java
  server/src/main/java/backend/section6mainproject/walklog/service/WalkLogServiceImpl.java
  server/src/main/resources/application.yml
  server/src/test/java/backend/section6mainproject/walklog/service/WalkLogServiceImplTest.java
Labels: 김승철, 기능

#46 43 be feat member delete 기능 구현
  server/src/main/java/backend/section6mainproject/member/controller/MemberController.java
  server/src/main/java/backend/section6mainproject/member/dto/MemberDTO.java
  server/src/main/java/backend/section6mainproject/member/service/MemberService.java
  server/src/main/java/backend/section6mainproject/member/service/MemberServiceImpl.java
Labels: 이재환, 기능

#40 Test: WalkLog get 기능 구현 (#31)
  server/src/main/java/backend/section6mainproject/TestDataInit.java
  server/src/main/java/backend/section6mainproject/coordinate/mapper/CoordinateMapper.java
  server/src/main/java/backend/section6mainproject/walklog/dto/WalkLogDTO.java
  server/src/main/java/backend/section6mainproject/walklog/mapper/WalkLogMapper.java
  server/src/test/java/backend/section6mainproject/walklog/controller/WalkLogControllerTest.java
  server/src/test/java/backend/section6mainproject/walklog/service/WalkLogServiceImplTest.java
Labels: 김성수, 테스트

#51 Feat, Test: WalkLog delete 기능 구현 (#49)
  server/src/main/java/backend/section6mainproject/walklog/controller/WalkLogController.java
  server/src/main/java/backend/section6mainproject/walklog/service/WalkLogService.java
  server/src/main/java/backend/section6mainproject/walklog/service/WalkLogServiceImpl.java
  server/src/test/java/backend/section6mainproject/walklog/controller/WalkLogControllerTest.java
  server/src/test/java/backend/section6mainproject/walklog/service/WalkLogServiceImplTest.java
Labels: 김성수, 기능, 테스트

#50 Refactor: 용도에 따라 다른 디렉토리에 사진을 저장하도록 수정 (#48)
  server/src/main/java/backend/section6mainproject/content/entity/WalkLogContent.java
  server/src/main/java/backend/section6mainproject/content/mapper/WalkLogContentMapper.java
  server/src/main/java/backend/section6mainproject/content/service/StorageService.java
  server/src/main/java/backend/section6mainproject/content/service/WalkLogContentServiceImpl.java
  server/src/main/java/backend/section6mainproject/helper/image/AWSS3StorageService.java
  server/src/main/java/backend/section6mainproject/helper/image/StorageService.java
Labels: 김승철, 리팩토링

#53 Feat: Member 조회 기능 (#45)
  server/src/main/java/backend/section6mainproject/member/controller/MemberController.java
  server/src/main/java/backend/section6mainproject/member/service/MemberService.java
  server/src/main/java/backend/section6mainproject/member/service/MemberServiceImpl.java
Labels: 이재환, 기능

#55 [FE] Feat: Modal Window 컴포넌트 구현
  client/.gitignore
  client/src/components/common/Modal.module.scss
  client/src/components/common/Modal.tsx
  client/src/components/common/Test.module.scss
  client/src/components/common/Test.tsx
  client/src/router/index.tsx
Labels: 하종승, 기능

#56 Feat: Member 조회시 응답으로 profileImage, 총 걷기 기록, 총 순간 기록 추가(#54)
  server/src/main/java/backend/section6mainproject/TestDataInit.java
  server/src/main/java/backend/section6mainproject/member/controller/MemberController.java
  server/src/main/java/backend/section6mainproject/member/dto/MemberDTO.java
  server/src/main/java/backend/section6mainproject/member/entity/Member.java
  server/src/main/java/backend/section6mainproject/member/mapper/MemberMapper.java
  server/src/main/java/backend/section6mainproject/member/service/MemberService.java
  server/src/main/java/backend/section6mainproject/member/service/MemberServiceImpl.java
Labels: 이재환, 기능

#58 Refactor: 웹소켓 요청시 진행중인 걷기 기록을 가져오고, 걷기 기록이 없으면 예외를 발생하도록 수정 (#57)
  server/src/main/java/backend/section6mainproject/coordinate/interceptor/ConnectionInterceptor.java
Labels: 김승철, 리팩토링

#61 Feat: MemberStatus == QUIT이면 조회,수정,삭제시 오류발생되는 로직구현(#60)
  server/src/main/java/backend/section6mainproject/member/controller/MemberController.java
  server/src/main/java/backend/section6mainproject/member/service/MemberServiceImpl.java
Labels: 이재환, 기능

#63 [FE] Feat: Sprite SVG로 Icon 컴포넌트 구현
  client/.eslintrc.cjs
  client/src/assets/sprite-icon.svg
  client/src/components/common/Icon.tsx
Labels: 허상범, 기능

#67 [FE] Feat: 걷는 중 순간 기록 페이지 구현
  client/src/components/OnWalk/Camera.module.scss
  client/src/components/OnWalk/Camera.tsx
  client/src/components/OnWalk/ImgInput.module.scss
  client/src/components/OnWalk/ImgInput.tsx
  client/src/components/OnWalk/SnapForm.module.scss
  client/src/components/OnWalk/SnapForm.tsx
Labels: 박설화, 기능

#70 [FE] 맵 컴포넌트 구현
  client/package-lock.json
  client/package.json
  client/src/components/common/Map.module.scss
  client/src/components/common/Map.tsx
  client/src/pages/Home.tsx
  client/src/router/index.tsx
Labels: 하종승, 기능, 테스트

#71 Chore: pr시 테스트 진행하는 설정파일 추가 (#69)
  .github/workflows/pr-test.yml
  server/src/test/java/backend/section6mainproject/walklog/service/WalkLogServiceImplTest.java
Labels: 김승철, 설정

#74 Feat: 예외 처리 기능 추가 (#47)
  server/src/main/java/backend/section6mainproject/advice/RestExceptionAdvice.java
  server/src/main/java/backend/section6mainproject/advice/StompExceptionAdvice.java
  server/src/main/java/backend/section6mainproject/coordinate/interceptor/ConnectionInterceptor.java
  server/src/main/java/backend/section6mainproject/coordinate/interceptor/SubscribeInterceptor.java
  server/src/main/java/backend/section6mainproject/exception/BusinessLogicException.java
  server/src/main/java/backend/section6mainproject/exception/ExceptionCode.java
  server/src/main/java/backend/section6mainproject/member/controller/MemberController.java
  server/src/main/java/backend/section6mainproject/member/service/MemberService.java
  server/src/main/java/backend/section6mainproject/member/service/MemberServiceImpl.java
  server/src/main/java/backend/section6mainproject/response/ErrorResponse.java
  server/src/main/java/backend/section6mainproject/walklog/service/WalkLogServiceImpl.java
  server/src/test/java/backend/section6mainproject/walklog/service/WalkLogServiceImplTest.java
Labels: 이재환, 기능

#75 Test: WalkLog 종료 기능 구현 (#52)
  server/src/main/java/backend/section6mainproject/exception/ExceptionCode.java
  server/src/main/java/backend/section6mainproject/walklog/controller/WalkLogController.java
  server/src/main/java/backend/section6mainproject/walklog/dto/WalkLogDTO.java
  server/src/main/java/backend/section6mainproject/walklog/service/WalkLogServiceImpl.java
  server/src/test/java/backend/section6mainproject/walklog/controller/WalkLogControllerTest.java
  server/src/test/java/backend/section6mainproject/walklog/service/WalkLogServiceImplTest.java
Labels: 김성수, 테스트

#77 Feat: JWT를 이용한 로그인 기능 구현 (#59)
  .github/workflows/pr-test.yml
  server/build.gradle
  server/src/main/java/backend/section6mainproject/TestDataInit.java
  server/src/main/java/backend/section6mainproject/auth/SecurityConfiguration.java
  server/src/main/java/backend/section6mainproject/auth/controller/AuthController.java
  server/src/main/java/backend/section6mainproject/auth/dto/LoginDTO.java
  server/src/main/java/backend/section6mainproject/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/backend/section6mainproject/auth/filter/JwtVerificationFilter.java
  server/src/main/java/backend/section6mainproject/auth/handler/AuthenticationSuccessHandlerUtils.java
  server/src/main/java/backend/section6mainproject/auth/handler/MemberAccessDeniedHandler.java
  server/src/main/java/backend/section6mainproject/auth/handler/MemberAuthenticationEntryHandler.java
  server/src/main/java/backend/section6mainproject/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/backend/section6mainproject/auth/jwt/JwtTokenizer.java
  server/src/main/java/backend/section6mainproject/auth/userdetails/MemberUserDetailsService.java
  server/src/main/java/backend/section6mainproject/auth/utils/CustomAuthorityUtils.java
  server/src/main/java/backend/section6mainproject/auth/utils/ErrorResponder.java
  server/src/main/java/backend/section6mainproject/member/entity/Member.java
  server/src/main/java/backend/section6mainproject/member/service/MemberServiceImpl.java
  server/src/main/resources/application.yml
Labels: 김승철, 기능

#83 Refactor: MemberController와 MemberService간 결합도 down 리팩터링 (#47)
  server/src/main/java/backend/section6mainproject/member/controller/MemberController.java
  server/src/main/java/backend/section6mainproject/member/dto/MemberDTO.java
  server/src/main/java/backend/section6mainproject/member/entity/Member.java
  server/src/main/java/backend/section6mainproject/member/mapper/MemberMapper.java
  server/src/main/java/backend/section6mainproject/member/service/MemberService.java
  server/src/main/java/backend/section6mainproject/member/service/MemberServiceImpl.java
Labels: 이재환, 기능

#84 76 be 걷기 전체 조회 기능 구현
  server/src/main/java/backend/section6mainproject/TestDataInit.java
  server/src/main/java/backend/section6mainproject/audit/Auditable.java
  server/src/main/java/backend/section6mainproject/content/dto/WalkLogContentDTO.java
  server/src/main/java/backend/section6mainproject/dto/MultiResponseDto.java
  server/src/main/java/backend/section6mainproject/dto/PageInfo.java
  server/src/main/java/backend/section6mainproject/exception/ExceptionCode.java
  server/src/main/java/backend/section6mainproject/member/controller/MemberController.java
  server/src/main/java/backend/section6mainproject/walklog/controller/WalkLogController.java
  server/src/main/java/backend/section6mainproject/walklog/dto/WalkLogDTO.java
  server/src/main/java/backend/section6mainproject/walklog/entity/WalkLog.java
  server/src/main/java/backend/section6mainproject/walklog/mapper/WalkLogMapper.java
  server/src/main/java/backend/section6mainproject/walklog/repository/WalkLogRepository.java
  server/src/main/java/backend/section6mainproject/walklog/service/WalkLogService.java
  server/src/main/java/backend/section6mainproject/walklog/service/WalkLogServiceImpl.java
  server/src/test/java/backend/section6mainproject/walklog/controller/WalkLogControllerTest.java
  server/src/test/java/backend/section6mainproject/walklog/service/WalkLogServiceImplTest.java
Labels: 김성수, 기능

#90 89 be fix 걷기 전체조회기능 버그 수정
  server/src/main/java/backend/section6mainproject/walklog/service/WalkLogServiceImpl.java
Labels: 김성수, 버그

#82 [FE] Feat: 기록 리스트 UI
  client/src/assets/sprite-icon.svg
  client/src/components/HistoryList/Calendar/Calendar.module.scss
  client/src/components/HistoryList/Calendar/Calendar.tsx
  client/src/components/HistoryList/Calendar/WeekDays.module.scss
  client/src/components/HistoryList/Calendar/WeekDays.tsx
  client/src/components/HistoryList/Calendar/YearMonth.module.scss
  client/src/components/HistoryList/Calendar/YearMonth.tsx
  client/src/components/HistoryList/History.module.scss
  client/src/components/HistoryList/History.tsx
  client/src/components/HistoryList/HistoryItem.module.scss
  client/src/components/HistoryList/HistoryItem.tsx
  client/src/components/OnWalk/ImgInput.module.scss
  client/src/components/common/Icon.tsx
  client/src/components/common/Map.module.scss
  client/src/pages/HistoryList.module.scss
  client/src/pages/HistoryList.tsx
  client/src/utils/ date.ts
Labels: 박설화, 기능

#92 [BE] Test: 웹소켓 기능 테스트
  server/build.gradle
  server/src/main/java/backend/section6mainproject/advice/RestExceptionAdvice.java
  server/src/main/java/backend/section6mainproject/advice/StompExceptionAdvice.java
  server/src/main/java/backend/section6mainproject/audit/Auditable.java
  server/src/main/java/backend/section6mainproject/coordinate/WebSocketBrokerConfig.java
  server/src/main/java/backend/section6mainproject/coordinate/controller/CoordinateController.java
  server/src/main/java/backend/section6mainproject/coordinate/dto/CoordinateControllerDTO.java
  server/src/main/java/backend/section6mainproject/coordinate/dto/CoordinateServiceDTO.java
  server/src/main/java/backend/section6mainproject/coordinate/entity/Coordinate.java
  server/src/main/java/backend/section6mainproject/coordinate/interceptor/ConnectionInterceptor.java
  server/src/main/java/backend/section6mainproject/coordinate/mapper/CoordinateMapper.java
  server/src/main/java/backend/section6mainproject/coordinate/service/CoordinateService.java
  server/src/main/java/backend/section6mainproject/coordinate/service/CoordinateServiceImpl.java
  server/src/main/java/backend/section6mainproject/response/ErrorResponse.java
  server/src/main/java/backend/section6mainproject/walklog/dto/WalkLogDTO.java
  server/src/test/java/backend/section6mainproject/coordinate/controller/CoordinateControllerTest.java
  server/src/test/java/backend/section6mainproject/coordinate/service/CoordinateServiceTest.java
  server/src/test/java/backend/section6mainproject/coordinate/socket/CoordinateSocketConnectionTest.java
Labels: 김승철, 버그, 테스트

#95 [FE] Feat: 데스크탑 대응 레이아웃 설정 & 이전 머지 디버깅
  client/src/components/HistoryList/History.module.scss
  client/src/components/HistoryList/History.tsx
  client/src/components/HistoryList/HistoryItem.module.scss
  client/src/components/HistoryList/HistoryItem.tsx
  client/src/components/OnWalk/ImgInput.module.scss
  client/src/components/OnWalk/ImgInput.tsx
  client/src/components/common/Modal.module.scss
  client/src/components/common/Modal.tsx
  client/src/pages/HistoryList.module.scss
  client/src/pages/HistoryList.tsx
  client/src/styles/_color.scss
  client/src/styles/_typography.scss
  client/src/styles/_utils.scss
  client/src/styles/global.scss
  client/src/utils/ date.ts
  client/src/utils/date.ts
Labels: 허상범, 리팩토링, 디자인

#100 Fix: 웹소켓 연결 테스트 시 웹소켓 스레드 대기시간 추가 (#99)
  server/src/test/java/backend/section6mainproject/coordinate/socket/CoordinateSocketConnectionTest.java
Labels: 김승철, 버그

#97 [FE] Feat: TapBar 구현 & Router 설정
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/common/Tapbar.module.scss
  client/src/components/common/Tapbar.tsx
  client/src/hooks/useRouter.ts
  client/src/layout/GeneralLayout.tsx
  client/src/main.tsx
  client/src/pages/SignIn.tsx
  client/src/pages/SignUp.tsx
  client/src/router/index.tsx
  client/src/router/routerData.tsx
  client/src/styles/_typography.scss
  client/src/types/TapBarElement.ts
Labels: 허상범, 기능, 리팩토링

#106 Feat: 비밀번호 유효성 검증 추가 (#105)
  server/src/main/java/backend/section6mainproject/member/dto/MemberControllerDTO.java
Labels: 이재환, 기능

#108 [BE] 걷기중 순간기록 등록 테스트
  server/src/main/java/backend/section6mainproject/content/controller/WalkLogContentController.java
  server/src/main/java/backend/section6mainproject/content/dto/WalkLogContentControllerDTO.java
  server/src/main/java/backend/section6mainproject/content/dto/WalkLogContentServiceDTO.java
  server/src/main/java/backend/section6mainproject/content/mapper/WalkLogContentMapper.java
  server/src/main/java/backend/section6mainproject/content/service/WalkLogContentService.java
  server/src/main/java/backend/section6mainproject/content/service/WalkLogContentServiceImpl.java
  server/src/main/java/backend/section6mainproject/coordinate/controller/CoordinateController.java
  server/src/main/java/backend/section6mainproject/coordinate/dto/CoordinateServiceDTO.java
  server/src/main/java/backend/section6mainproject/coordinate/mapper/CoordinateMapper.java
  server/src/main/java/backend/section6mainproject/coordinate/service/CoordinateService.java
  server/src/main/java/backend/section6mainproject/coordinate/service/CoordinateServiceImpl.java
  server/src/main/java/backend/section6mainproject/walklog/dto/WalkLogDTO.java
  server/src/test/java/backend/section6mainproject/content/WalkLogContentStubData.java
  server/src/test/java/backend/section6mainproject/content/controller/WalkLogContentControllerTest.java
  server/src/test/java/backend/section6mainproject/content/service/WalkLogContentServiceTest.java
  server/src/test/java/backend/section6mainproject/coordinate/controller/CoordinateControllerTest.java
  server/src/test/java/backend/section6mainproject/coordinate/service/CoordinateServiceTest.java
  server/src/test/resources/testImage/test.jpg
Labels: 김승철, 테스트

#114 [BE] 걷기중 순간기록 수정
  server/src/main/java/backend/section6mainproject/advice/RestExceptionAdvice.java
  server/src/main/java/backend/section6mainproject/content/controller/WalkLogContentController.java
  server/src/main/java/backend/section6mainproject/content/dto/WalkLogContentControllerDTO.java
  server/src/main/java/backend/section6mainproject/content/dto/WalkLogContentServiceDTO.java
  server/src/main/java/backend/section6mainproject/content/mapper/WalkLogContentMapper.java
  server/src/main/java/backend/section6mainproject/content/service/WalkLogContentService.java
  server/src/main/java/backend/section6mainproject/content/service/WalkLogContentServiceImpl.java
  server/src/main/java/backend/section6mainproject/exception/ExceptionCode.java
  server/src/main/java/backend/section6mainproject/helper/image/AWSS3StorageService.java
  server/src/test/java/backend/section6mainproject/content/WalkLogContentStubData.java
  server/src/test/java/backend/section6mainproject/content/controller/WalkLogContentControllerTest.java
  server/src/test/java/backend/section6mainproject/content/service/WalkLogContentServiceTest.java
Labels: 김승철, 기능, 테스트

#118 [BE] 웹소켓 테스트 관련 오류 수정
  server/src/main/java/backend/section6mainproject/helper/image/AWSS3StorageService.java
  server/src/test/java/backend/section6mainproject/coordinate/socket/CoordinateSocketConnectionTest.java
Labels: 김승철, 버그

#115 Test: MemberController 슬라이스 테스트 작성 및 mapper 메소드네임 변경 (#85)
  server/src/main/java/backend/section6mainproject/member/controller/MemberController.java
  server/src/main/java/backend/section6mainproject/member/dto/MemberControllerDTO.java
  server/src/main/java/backend/section6mainproject/member/dto/MemberServiceDTO.java
  server/src/main/java/backend/section6mainproject/member/mapper/MemberMapper.java
  server/src/main/java/backend/section6mainproject/member/service/MemberService.java
  server/src/main/java/backend/section6mainproject/member/service/MemberServiceImpl.java
  server/src/test/java/backend/section6mainproject/member/controller/MemberControllerTest.java
  server/src/test/java/backend/section6mainproject/member/service/MemberServiceImpleTest.java
  server/src/test/resources/imageSource/블랙홀.jpeg
Labels: 이재환, 리팩토링, 테스트

#121 [BE] 걷기 중 순간기록 삭제
  server/src/main/java/backend/section6mainproject/content/controller/WalkLogContentController.java
  server/src/main/java/backend/section6mainproject/content/service/WalkLogContentService.java
  server/src/main/java/backend/section6mainproject/content/service/WalkLogContentServiceImpl.java
  server/src/test/java/backend/section6mainproject/content/controller/WalkLogContentControllerTest.java
  server/src/test/java/backend/section6mainproject/content/service/WalkLogContentServiceTest.java
Labels: 김승철, 기능

#126 Refactor: 비즈니스 로직 예외 발생시 로깅 추가 (#125)
  server/src/main/java/backend/section6mainproject/content/dto/WalkLogContentControllerDTO.java
  server/src/main/java/backend/section6mainproject/coordinate/interceptor/ConnectionInterceptor.java
  server/src/main/java/backend/section6mainproject/coordinate/interceptor/SubscribeInterceptor.java
  server/src/main/java/backend/section6mainproject/exception/BusinessLogicException.java
Labels: 김승철, 리팩토링

#124 123 refactor walklog 코드 리팩토링
  server/src/main/java/backend/section6mainproject/member/controller/MemberController.java
  server/src/main/java/backend/section6mainproject/walklog/controller/WalkLogController.java
  server/src/main/java/backend/section6mainproject/walklog/dto/WalkLogControllerDTO.java
  server/src/main/java/backend/section6mainproject/walklog/dto/WalkLogServiceDTO.java
  server/src/main/java/backend/section6mainproject/walklog/mapper/WalkLogMapper.java
  server/src/main/java/backend/section6mainproject/walklog/repository/WalkLogRepository.java
  server/src/main/java/backend/section6mainproject/walklog/service/WalkLogService.java
  server/src/main/java/backend/section6mainproject/walklog/service/WalkLogServiceImpl.java
  server/src/test/java/backend/section6mainproject/walklog/controller/WalkLogControllerTest.java
  server/src/test/java/backend/section6mainproject/walklog/service/WalkLogServiceImplTest.java
Labels: 김성수, 리팩토링

#130 Fix: 탈퇴된 회원 로그인 안되도록 수정 (#129)
  server/src/main/java/backend/section6mainproject/auth/userdetails/MemberUserDetailsService.java
  server/src/main/java/backend/section6mainproject/member/repository/MemberRepository.java
Labels: 김승철, 버그

#116 [FE] Refactor: 기록리스트 & 달력 컴포넌츠 리팩토링
  client/package-lock.json
  client/package.json
  client/src/components/HistoryList/Calendar/Calendar.module.scss
  client/src/components/HistoryList/Calendar/Calendar.tsx
  client/src/components/HistoryList/Calendar/Dates.module.scss
  client/src/components/HistoryList/Calendar/Dates.tsx
  client/src/components/HistoryList/Calendar/WeekDays.module.scss
  client/src/components/HistoryList/Calendar/WeekDays.tsx
  client/src/components/HistoryList/Calendar/YearMonth.tsx
  client/src/components/HistoryList/Calendar/date-fns.ts
  client/src/components/HistoryList/History.tsx
  client/src/components/HistoryList/HistoryItem.tsx
  client/src/components/HistoryList/Toggle.module.scss
  client/src/components/HistoryList/Toggle.tsx
  client/src/components/OnWalk/Camera.tsx
  client/src/components/OnWalk/SnapForm.tsx
  client/src/components/common/Icon.tsx
  client/src/components/common/Map.tsx
  client/src/components/common/Modal.tsx
  client/src/pages/HistoryList.module.scss
  client/src/pages/HistoryList.tsx
Labels: 박설화, 기능, 리팩토링

#132 Refactor: 리프레시 토큰 쿠키로 보내도록 수정 (#131)
  server/src/main/java/backend/section6mainproject/auth/filter/JwtVerificationFilter.java
  server/src/main/java/backend/section6mainproject/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/test/java/backend/section6mainproject/coordinate/socket/CoordinateSocketConnectionTest.java
Labels: 김승철, 리팩토링

#133 feat: 내 걷기기록 전체조회 페이지가 없는 버전 추가(#127)
  server/src/main/java/backend/section6mainproject/member/controller/MemberController.java
  server/src/main/java/backend/section6mainproject/walklog/controller/WalkLogController.java
  server/src/main/java/backend/section6mainproject/walklog/dto/WalkLogControllerDTO.java
  server/src/main/java/backend/section6mainproject/walklog/dto/WalkLogServiceDTO.java
  server/src/main/java/backend/section6mainproject/walklog/mapper/WalkLogMapper.java
  server/src/main/java/backend/section6mainproject/walklog/repository/WalkLogRepository.java
  server/src/main/java/backend/section6mainproject/walklog/service/WalkLogService.java
  server/src/main/java/backend/section6mainproject/walklog/service/WalkLogServiceImpl.java
Labels: 김성수, 기능

#137 Refactor: WalkLogControllerDTO 유효성검증 추가(#135)
  server/src/main/java/backend/section6mainproject/walklog/dto/WalkLogControllerDTO.java
Labels: 김성수, 리팩토링

#141 Feat: 이미지파일 용량 제한 (#128)
  server/src/main/java/backend/section6mainproject/advice/RestExceptionAdvice.java
  server/src/main/resources/application.yml
Labels: 이재환, 기능

#144 Feat&Test: 회원 패스워드 수정기능 분리 및 테스트코드작성 (#128)
  server/src/main/java/backend/section6mainproject/advice/RestExceptionAdvice.java
  server/src/main/java/backend/section6mainproject/member/controller/MemberController.java
  server/src/main/java/backend/section6mainproject/member/dto/MemberServiceDTO.java
  server/src/main/java/backend/section6mainproject/member/mapper/MemberMapper.java
  server/src/main/java/backend/section6mainproject/member/service/MemberService.java
  server/src/main/java/backend/section6mainproject/member/service/MemberServiceImpl.java
  server/src/test/java/backend/section6mainproject/member/controller/MemberControllerTest.java
  server/src/test/java/backend/section6mainproject/member/service/MemberServiceTest.java
Labels: 이재환, 기능, 테스트

#134 [FE] Feat: 기록 상세페이지 UI
  client/src/assets/sprite-icon.svg
  client/src/components/HistoryDetail/DetailItem.module.scss
  client/src/components/HistoryDetail/DetailItem.tsx
  client/src/components/HistoryDetail/ImgModal.module.scss
  client/src/components/HistoryDetail/ImgModal.tsx
  client/src/components/HistoryDetail/Title.module.scss
  client/src/components/HistoryDetail/Title.tsx
  client/src/components/HistoryList/Calendar/Calendar.tsx
  client/src/components/HistoryList/Calendar/Dates.tsx
  client/src/components/HistoryList/Calendar/YearMonth.tsx
  client/src/components/HistoryList/History.module.scss
  client/src/components/HistoryList/History.tsx
  client/src/components/OnWalk/ImgInput.tsx
  client/src/components/OnWalk/SnapForm.module.scss
  client/src/components/OnWalk/SnapForm.tsx
  client/src/components/common/DropDown.module.scss
  client/src/components/common/DropDown.tsx
  client/src/components/common/Icon.tsx
  client/src/pages/HistoryDetail.module.scss
  client/src/pages/HistoryDetail.tsx
  client/src/store/authAtom.ts
  client/src/utils/date-fns.ts
  client/src/utils/date.ts
Labels: 박설화, 기능

#148 Refactor: 내 걷기기록 조회 리팩토링(#140)
  server/src/main/java/backend/section6mainproject/exception/ExceptionCode.java
  server/src/main/java/backend/section6mainproject/member/controller/MemberController.java
  server/src/main/java/backend/section6mainproject/walklog/repository/WalkLogRepository.java
  server/src/main/java/backend/section6mainproject/walklog/service/WalkLogServiceImpl.java
Labels: 김성수, 리팩토링

#151 [BE] 걷기 중 순간기록 api 문서화
  server/build.gradle
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/backend/section6mainproject/content/controller/WalkLogContentController.java
  server/src/test/java/backend/section6mainproject/content/WalkLogContentStubData.java
  server/src/test/java/backend/section6mainproject/content/controller/WalkLogContentControllerTest.java
  server/src/test/java/backend/section6mainproject/util/ApiDocumentUtils.java
Labels: 김승철, 문서

#145 [FE] Feat: Google Map 설정
  client/.eslintrc.cjs
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/common/Map/MapCanvas.tsx
  client/src/contexts/mapRefContext.ts
  client/src/hooks/useMapRef.ts
  client/src/hooks/useMarker.ts
  client/src/hooks/usePolyline.ts
  client/src/styles/_googlemap.scss
  client/src/styles/global.scss
Labels: 허상범, 기능

#155 [BE] 회원 API 문서화
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/backend/section6mainproject/member/dto/MemberControllerDTO.java
  server/src/test/java/backend/section6mainproject/member/MemberStubData.java
  server/src/test/java/backend/section6mainproject/member/controller/MemberControllerTest.java
  server/src/test/resources/imageSource/블랙홀.jpeg
Labels: 김승철, 문서

#160 149 be test 내 걷기기록 조회 테스트코드 구현
  server/src/main/java/backend/section6mainproject/exception/ExceptionCode.java
  server/src/main/java/backend/section6mainproject/member/controller/MemberController.java
  server/src/main/java/backend/section6mainproject/walklog/dto/WalkLogControllerDTO.java
  server/src/main/java/backend/section6mainproject/walklog/mapper/WalkLogMapper.java
  server/src/test/java/backend/section6mainproject/member/controller/MemberControllerTest.java
  server/src/test/java/backend/section6mainproject/walklog/service/WalkLogServiceImplTest.java
Labels: 김성수, 테스트

#163 [FE] Feat: 기록 상세페이지 api
  client/src/apis/history.ts
  client/src/apis/user.ts
  client/src/assets/sprite-icon.svg
  client/src/components/ChangePassword/ChangingPassword.tsx
  client/src/components/ChangePassword/PasswordChanged.tsx
  client/src/components/HistoryDetail/DetailItem.tsx
  client/src/components/HistoryDetail/Title.module.scss
  client/src/components/HistoryDetail/Title.tsx
  client/src/components/MyPage/EditProfile.tsx
  client/src/components/MyPage/ProfileImgInput.module.scss
  client/src/components/OnWalk/ImgInput.tsx
  client/src/components/OnWalk/SnapForm.tsx
  client/src/components/SignUp/TermsOfUse.module.scss
  client/src/components/common/Icon.tsx
  client/src/pages/HistoryDetail.tsx
  client/src/pages/MyPage.tsx
  client/src/types/HistoryDetail.ts
Labels: 박설화, 기능

#166 [FE] Fix: 로그인 실패 시에도 성공으로 인식되는 이슈 해결
  client/src/apis/user.ts
  client/src/pages/SignUp.tsx
Labels: 하종승, 버그

#173 Setting: 걷기기록 관련 더미데이터 추가(#168)
  server/src/main/java/backend/section6mainproject/TestDataInit.java
  server/src/main/java/backend/section6mainproject/audit/Auditable.java
  server/src/main/java/backend/section6mainproject/walklog/dto/WalkLogControllerDTO.java
Labels: 김성수, 설정

#177 156 be feat 걷기기록 피드 조회 구현
  server/src/main/java/backend/section6mainproject/member/controller/MemberController.java
  server/src/main/java/backend/section6mainproject/walklog/controller/WalkLogController.java
  server/src/main/java/backend/section6mainproject/walklog/dto/WalkLogControllerDTO.java
  server/src/main/java/backend/section6mainproject/walklog/dto/WalkLogServiceDTO.java
  server/src/main/java/backend/section6mainproject/walklog/mapper/WalkLogMapper.java
  server/src/main/java/backend/section6mainproject/walklog/repository/WalkLogRepository.java
  server/src/main/java/backend/section6mainproject/walklog/service/WalkLogService.java
  server/src/main/java/backend/section6mainproject/walklog/service/WalkLogServiceImpl.java
  server/src/test/java/backend/section6mainproject/member/controller/MemberControllerTest.java
  server/src/test/java/backend/section6mainproject/walklog/controller/WalkLogControllerTest.java
  server/src/test/java/backend/section6mainproject/walklog/service/WalkLogServiceImplTest.java
Labels: 김성수, 기능, 테스트

#178 [BE] api요청시 토큰 인증 요건 추가
  server/src/main/java/backend/section6mainproject/TestDataInit.java
  server/src/main/java/backend/section6mainproject/auth/SecurityConfiguration.java
  server/src/main/java/backend/section6mainproject/auth/handler/AuthenticationSuccessHandlerUtils.java
  server/src/main/java/backend/section6mainproject/coordinate/interceptor/ConnectionInterceptor.java
  server/src/main/java/backend/section6mainproject/walklog/controller/WalkLogController.java
  server/src/main/java/backend/section6mainproject/walklog/dto/WalkLogControllerDTO.java
  server/src/main/java/backend/section6mainproject/walklog/dto/WalkLogServiceDTO.java
  server/src/main/java/backend/section6mainproject/walklog/mapper/WalkLogMapper.java
  server/src/test/java/backend/section6mainproject/coordinate/controller/CoordinateControllerTest.java
  server/src/test/java/backend/section6mainproject/coordinate/socket/CoordinateSocketConnectionTest.java
  server/src/test/java/backend/section6mainproject/walklog/controller/WalkLogControllerTest.java
  server/src/test/java/backend/section6mainproject/walklog/service/WalkLogServiceImplTest.java
Labels: 김승철, 기능

#180 Fix: 걷기 종료시 순간기록이 없으면 종료가 안되는 문제 수정 (#179)
  server/src/main/java/backend/section6mainproject/walklog/service/WalkLogServiceImpl.java
Labels: 김성수, 버그

#174 Feat: 이메일 전송 구현 (#147)
  .github/workflows/pr-test.yml
  server/build.gradle
  server/src/main/java/backend/section6mainproject/Section6MainProjectApplication.java
  server/src/main/java/backend/section6mainproject/helper/email/EmailConfiguration.java
  server/src/main/java/backend/section6mainproject/helper/email/EmailSendable.java
  server/src/main/java/backend/section6mainproject/helper/email/EmailSender.java
  server/src/main/java/backend/section6mainproject/helper/email/SimpleEmailSendable.java
  server/src/main/java/backend/section6mainproject/helper/email/TemplateEmailSendable.java
  server/src/main/java/backend/section6mainproject/helper/event/PasswordResetEvent.java
  server/src/main/java/backend/section6mainproject/helper/event/PasswordResetEventListner.java
  server/src/main/java/backend/section6mainproject/member/controller/MemberController.java
  server/src/main/java/backend/section6mainproject/member/dto/MemberControllerDTO.java
  server/src/main/java/backend/section6mainproject/member/dto/MemberServiceDTO.java
  server/src/main/java/backend/section6mainproject/member/mapper/MemberMapper.java
  server/src/main/java/backend/section6mainproject/member/repository/MemberRepository.java
  server/src/main/java/backend/section6mainproject/member/service/MemberService.java
  server/src/main/java/backend/section6mainproject/member/service/MemberServiceImpl.java
  server/src/main/resources/application.yml
  server/src/main/resources/templates/email-password-reset.html
  server/src/test/java/backend/section6mainproject/member/controller/MemberControllerTest.java
Labels: 이재환, 기능

#181 157 be refactor walklog 테스트 코드 리팩토링
  server/src/main/java/backend/section6mainproject/walklog/dto/WalkLogControllerDTO.java
  server/src/main/java/backend/section6mainproject/walklog/entity/WalkLog.java
  server/src/main/java/backend/section6mainproject/walklog/mapper/WalkLogMapper.java
  server/src/main/java/backend/section6mainproject/walklog/service/WalkLogService.java
  server/src/main/java/backend/section6mainproject/walklog/service/WalkLogServiceImpl.java
  server/src/test/java/backend/section6mainproject/walklog/WalkLogStubData.java
  server/src/test/java/backend/section6mainproject/walklog/controller/WalkLogControllerTest.java
  server/src/test/java/backend/section6mainproject/walklog/service/WalkLogServiceImplTest.java
  server/src/test/java/backend/section6mainproject/walklog/walkLogStubData.java
Labels: 김성수, 리팩토링

#171 [FE] Feat: 이메일 유효성 검증 방식 변경
  client/src/pages/SignUp.tsx
Labels: 하종승, 버그

#175 [FE] Feat: 비밀번호 찾기 기능
  client/src/apis/user.ts
  client/src/components/FindPassword/TempPasswordSent.module.scss
  client/src/components/FindPassword/TempPasswordSent.tsx
  client/src/pages/FindPassword.module.scss
  client/src/pages/FindPassword.tsx
  client/src/pages/SignIn.tsx
  client/src/pages/SignUp.tsx
  client/src/router/routerData.tsx
  client/vite.config.ts
Labels: 하종승, 기능

#182 [FE] Fix: signin response 변경
  client/src/apis/user.ts
  client/src/pages/SignIn.tsx
Labels: 하종승, 버그

#186 [BE] 로그아웃 기능 구현
  server/src/main/java/backend/section6mainproject/auth/SecurityConfiguration.java
  server/src/main/java/backend/section6mainproject/auth/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/backend/section6mainproject/coordinate/interceptor/ConnectionInterceptor.java
  server/src/main/java/backend/section6mainproject/member/service/MemberService.java
  server/src/main/java/backend/section6mainproject/member/service/MemberServiceImpl.java
  server/src/main/java/backend/section6mainproject/walklog/controller/WalkLogController.java
  server/src/main/java/backend/section6mainproject/walklog/dto/WalkLogServiceDTO.java
  server/src/test/java/backend/section6mainproject/coordinate/controller/CoordinateControllerTest.java
  server/src/test/java/backend/section6mainproject/coordinate/socket/CoordinateSocketConnectionTest.java
  server/src/test/java/backend/section6mainproject/member/MemberStubData.java
  server/src/test/java/backend/section6mainproject/member/service/MemberServiceTest.java
  server/src/test/java/backend/section6mainproject/walklog/WalkLogStubData.java
  server/src/test/java/backend/section6mainproject/walklog/controller/WalkLogControllerTest.java
Labels: 김승철, 기능

#185 [FE] Feat: 회원 탈퇴 기능
  client/src/apis/user.ts
  client/src/pages/MyPage.tsx
Labels: 하종승, 기능

#187 [FE] Feat: 헤더 컴포넌트
  client/package-lock.json
  client/package.json
  client/src/components/common/Header.module.scss
  client/src/components/common/Header.tsx
  client/src/pages/ChangePassword.tsx
  client/src/pages/FindPassword.tsx
  client/src/pages/HistoryDetail.tsx
  client/src/pages/SignIn.tsx
  client/src/pages/SignUp.tsx
  client/vite.config.ts
Labels: 하종승, 기능

#188 [FE] Feat: 기록 리스트 API 연결
  client/src/apis/history.ts
  client/src/components/HistoryDetail/DetailItem.tsx
  client/src/components/HistoryList/Calendar/Calendar.tsx
  client/src/components/HistoryList/Calendar/Dates.tsx
  client/src/components/HistoryList/History.module.scss
  client/src/components/HistoryList/History.tsx
  client/src/components/HistoryList/HistoryItem.tsx
  client/src/pages/HistoryDetail.tsx
  client/src/pages/HistoryList.tsx
  client/src/types/History.ts
  client/src/types/HistoryDetail.ts
  client/src/utils/date-fns.ts
Labels: 박설화, 기능

#190 [BE] 리소스 주체 검증 기능 추가
  server/src/main/java/backend/section6mainproject/advice/MemberVerifyAdvice.java
  server/src/main/java/backend/section6mainproject/advice/RestExceptionAdvice.java
  server/src/main/java/backend/section6mainproject/coordinate/interceptor/SubscribeInterceptor.java
  server/src/main/java/backend/section6mainproject/member/controller/MemberController.java
  server/src/main/java/backend/section6mainproject/member/dto/MemberControllerDTO.java
  server/src/main/java/backend/section6mainproject/member/repository/MemberRepository.java
  server/src/test/java/backend/section6mainproject/coordinate/socket/CoordinateSocketConnectionTest.java
Labels: 김승철, 기능

#196 [BE] 걷기 기록, 순간 기록수 계산 로직 개선
  server/src/main/java/backend/section6mainproject/content/repository/WalkLogContentRepository.java
  server/src/main/java/backend/section6mainproject/member/dto/MemberControllerDTO.java
  server/src/main/java/backend/section6mainproject/member/dto/MemberServiceDTO.java
  server/src/main/java/backend/section6mainproject/member/mapper/MemberMapper.java
  server/src/main/java/backend/section6mainproject/walklog/repository/WalkLogRepository.java
  server/src/test/java/backend/section6mainproject/walklog/WalkLogStubData.java
  server/src/test/java/backend/section6mainproject/walklog/repository/WalkLogRepositoryTest.java
Labels: 김승철, 리팩토링

#201 158 be docs walklog api 문서화
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/backend/section6mainproject/TestDataInit.java
  server/src/main/java/backend/section6mainproject/walklog/dto/WalkLogControllerDTO.java
  server/src/test/java/backend/section6mainproject/member/controller/MemberControllerTest.java
  server/src/test/java/backend/section6mainproject/walklog/WalkLogStubData.java
  server/src/test/java/backend/section6mainproject/walklog/controller/WalkLogControllerTest.java
Labels: 김성수, 문서

#206 [FE] Feat: axios 인스턴스
  client/.env.development
  client/.env.production
  client/src/apis/instance.ts
  client/src/apis/user.ts
  client/src/apis/walkLog.ts
  client/src/components/ChangePassword/ChangingPassword.tsx
  client/src/components/ChangePassword/PasswordChanged.tsx
  client/src/components/MyPage/EditProfile.tsx
  client/src/components/SignUp/TermsOfUse.tsx
  client/src/components/common/DropDown.tsx
  client/src/layout/GeneralLayout.tsx
  client/src/pages/ChangePassword.tsx
  client/src/pages/MyPage.tsx
  client/vite.config.ts
Labels: 하종승, 기능

#204 167 be setting 도메인연결 및 rds ec2 연결
  .github/workflows/pr-test.yml
  server/build.gradle
  server/src/main/java/backend/section6mainproject/TestDataInit.java
  server/src/main/resources/application-local.yml
  server/src/main/resources/application-server.yml
  server/src/main/resources/application.yml
Labels: 김성수, 설정

#210 [FE] Refactor: user 요청 URL 변경
  client/.env.development
  client/.env.production
  client/.gitignore
  client/src/apis/user.ts
  client/src/components/ChangePassword/ChangingPassword.tsx
  client/src/components/MyPage/EditProfile.tsx
  client/src/components/common/Header.tsx
  client/src/layout/GeneralLayout.tsx
  client/src/pages/FindPassword.tsx
  client/src/pages/HistoryDetail.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/SignIn.tsx
Labels: 하종승, 리팩토링

#212 [FE] Refactor history axios 개발/배포모드설정
  client/src/apis/history.ts
  client/src/components/HistoryDetail/DetailItem.tsx
  client/src/components/HistoryDetail/Title.tsx
  client/src/components/common/Header.tsx
  client/src/hooks/useRouter.ts
  client/src/pages/HistoryDetail.tsx
Labels: 박설화, 기능

#209 Refactor: 응답 데이터 멤버 프로필 사진 추가 및 관련로직 변경(#203)
  server/src/main/java/backend/section6mainproject/walklog/controller/WalkLogController.java
  server/src/main/java/backend/section6mainproject/walklog/dto/WalkLogControllerDTO.java
  server/src/main/java/backend/section6mainproject/walklog/dto/WalkLogServiceDTO.java
  server/src/main/java/backend/section6mainproject/walklog/mapper/WalkLogMapper.java
  server/src/main/java/backend/section6mainproject/walklog/service/WalkLogService.java
  server/src/main/java/backend/section6mainproject/walklog/service/WalkLogServiceImpl.java
  server/src/main/resources/application.yml
  server/src/test/java/backend/section6mainproject/walklog/WalkLogStubData.java
  server/src/test/java/backend/section6mainproject/walklog/controller/WalkLogControllerTest.java
  server/src/test/java/backend/section6mainproject/walklog/service/WalkLogServiceImplTest.java
Labels: 김성수, 리팩토링

#215 Feat: 회원가입 및 회원수정시 닉네임 중복 예외처리 with 409 (#214)
  server/src/main/java/backend/section6mainproject/exception/ExceptionCode.java
  server/src/main/java/backend/section6mainproject/member/repository/MemberRepository.java
  server/src/main/java/backend/section6mainproject/member/service/MemberServiceImpl.java
Labels: 이재환, 기능

#219 [BE] profile api 추가
  server/src/main/java/backend/section6mainproject/TestDataInit.java
  server/src/main/java/backend/section6mainproject/auth/SecurityConfiguration.java
  server/src/main/java/backend/section6mainproject/auth/controller/AuthController.java
  server/src/test/java/backend/section6mainproject/coordinate/socket/CoordinateSocketConnectionTest.java
Labels: 김승철, 기능

#223 Fix: 1건의 걷기기록 조회 WalkLogStatus 추가(#221)
  server/src/main/java/backend/section6mainproject/walklog/dto/WalkLogControllerDTO.java
  server/src/main/java/backend/section6mainproject/walklog/dto/WalkLogServiceDTO.java
  server/src/test/java/backend/section6mainproject/walklog/WalkLogStubData.java
  server/src/test/java/backend/section6mainproject/walklog/controller/WalkLogControllerTest.java
Labels: 김성수, 기능

#222 217 be 수정 요청시 기존 이미지파일이 삭제되는 문제 해결
  server/src/main/java/backend/section6mainproject/content/service/WalkLogContentServiceImpl.java
  server/src/main/java/backend/section6mainproject/member/service/MemberServiceImpl.java
Labels: 김성수, 기능

#225 Bug: 패스워드 수정 유효성 검증 장착 (#224)
  server/src/main/java/backend/section6mainproject/member/controller/MemberController.java
Labels: 이재환, 버그

#226 [FE] Feat: 자동 로그인 기능 및 버그 수정
  client/src/apis/user.ts
  client/src/components/MyPage/EditProfile.tsx
  client/src/components/MyPage/ProfileImgInput.tsx
  client/src/layout/GeneralLayout.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/SignIn.tsx
  client/src/router/index.tsx
  client/src/utils/refreshTokenHandler.ts
  client/vite.config.ts
Labels: 하종승, 기능, 버그

#227 [BE] 비회원 걷기 기록 조회
  server/src/main/java/backend/section6mainproject/advice/MemberVerifyAdvice.java
  server/src/main/java/backend/section6mainproject/advice/StompExceptionAdvice.java
  server/src/main/java/backend/section6mainproject/coordinate/controller/CoordinateController.java
  server/src/main/java/backend/section6mainproject/coordinate/mapper/AnonymousCoordinateMapper.java
  server/src/main/java/backend/section6mainproject/walklog/controller/AnonymousWalkLogController.java
  server/src/main/java/backend/section6mainproject/walklog/dto/AnonymousWalkLogControllerDTO.java
  server/src/main/java/backend/section6mainproject/walklog/dto/AnonymousWalkLogServiceDTO.java
  server/src/main/java/backend/section6mainproject/walklog/entity/AnonymousWalkLog.java
  server/src/main/java/backend/section6mainproject/walklog/mapper/AnonymousWalkLogMapper.java
  server/src/main/java/backend/section6mainproject/walklog/service/AnonymousWalkLogService.java
  server/src/main/java/backend/section6mainproject/walklog/service/AnonymousWalkLogServiceImpl.java
  server/src/test/java/backend/section6mainproject/coordinate/socket/CoordinateSocketConnectionTest.java
Labels: 김승철, 기능

#231 Fix: 빌드 시도 시 오류나는 부분 해결하기 (#230)
  client/src/components/HistoryDetail/Title.tsx
  client/src/components/MyPage/EditProfile.tsx
  client/src/layout/GeneralLayout.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/SignIn.tsx
Labels: 허상범, 버그

#238 Fix:걷기 종료시 mapImage가 정상적으로 저장되지 않는 현상 수정 (#237)
  server/src/main/java/backend/section6mainproject/walklog/controller/WalkLogController.java
  server/src/main/java/backend/section6mainproject/walklog/dto/WalkLogControllerDTO.java
  server/src/main/java/backend/section6mainproject/walklog/mapper/WalkLogMapper.java
  server/src/main/java/backend/section6mainproject/walklog/service/WalkLogServiceImpl.java
  server/src/test/java/backend/section6mainproject/walklog/controller/WalkLogControllerTest.java
Labels: 김성수, 버그

#239 [BE] 비회원 걷기 기록 종료
  server/src/main/java/backend/section6mainproject/TestDataInit.java
  server/src/main/java/backend/section6mainproject/advice/MemberVerifyAdvice.java
  server/src/main/java/backend/section6mainproject/advice/RestExceptionAdvice.java
  server/src/main/java/backend/section6mainproject/walklog/controller/AnonymousWalkLogController.java
  server/src/main/java/backend/section6mainproject/walklog/service/AnonymousWalkLogService.java
  server/src/main/java/backend/section6mainproject/walklog/service/AnonymousWalkLogServiceImpl.java
  server/src/test/java/backend/section6mainproject/coordinate/socket/CoordinateSocketConnectionTest.java
Labels: 김승철, 기능

#232 Feat: page 없이 걷기피드조회시 예외처리 추가 (#228)
  server/src/main/java/backend/section6mainproject/advice/RestExceptionAdvice.java
  server/src/main/java/backend/section6mainproject/advice/StompExceptionAdvice.java
  server/src/main/java/backend/section6mainproject/walklog/dto/WalkLogControllerDTO.java
  server/src/main/java/backend/section6mainproject/walklog/service/WalkLogServiceImpl.java
Labels: 이재환, 기능

#234 [FE] Feat: 피드 컴포넌트 구현
  client/src/apis/walkLog.ts
  client/src/assets/sprite-icon.svg
  client/src/components/Feed/FeedItem.module.scss
  client/src/components/Feed/FeedItem.tsx
  client/src/components/Feed/SnapItem.module.scss
  client/src/components/Feed/SnapItem.tsx
  client/src/components/HistoryList/History.tsx
  client/src/components/common/Icon.tsx
  client/src/pages/Feed.module.scss
  client/src/pages/Feed.tsx
  client/src/utils/date-fns.ts
  client/src/utils/date.ts
Labels: 하종승, 기능

#236 [FE] Feat: 로그아웃 기능 구현
  client/src/apis/user.ts
  client/src/pages/MyPage.module.scss
  client/src/pages/MyPage.tsx
  client/vite.config.ts
Labels: 하종승, 기능

#244 [BE] 데이터 삭제시 사진이 삭제되지 않는 오류 수정
  server/src/main/java/backend/section6mainproject/auth/SecurityConfiguration.java
  server/src/main/java/backend/section6mainproject/content/service/WalkLogContentServiceImpl.java
  server/src/main/java/backend/section6mainproject/helper/image/AWSS3StorageService.java
  server/src/main/java/backend/section6mainproject/helper/image/StorageService.java
  server/src/main/java/backend/section6mainproject/member/service/MemberServiceImpl.java
  server/src/main/java/backend/section6mainproject/walklog/service/WalkLogServiceImpl.java
Labels: 김승철, 기능

#248 Fix: Cors 설정 변경 (#247)
  server/src/main/java/backend/section6mainproject/auth/SecurityConfiguration.java
Labels: 김승철, 버그

#243 [FE] Fix 걷기기록 한줄메시지 수정하기 에러수정
  client/src/components/HistoryDetail/Title.tsx
  client/src/components/OnWalk/ImgInput.tsx
  client/src/components/OnWalk/SnapForm.tsx
  client/src/components/common/DropDown.module.scss
  client/src/components/common/DropDown.tsx
Labels: 박설화, 리팩토링, 버그

#251 [FE] Fix: 마이페이지 버그 수정
  client/src/components/MyPage/EditProfile.tsx
  client/src/components/MyPage/ProfileImgInput.tsx
  client/src/pages/MyPage.module.scss
  client/src/pages/MyPage.tsx
Labels: 하종승, 버그

#257 Fix: 쿠키 설정 변경 (#256)
  server/src/main/java/backend/section6mainproject/auth/handler/MemberAuthenticationSuccessHandler.java
Labels: 김승철, 버그

#259 256 be fix 쿠키 조회 안되는 문제 수정
  server/src/main/java/backend/section6mainproject/auth/handler/MemberAuthenticationSuccessHandler.java
Labels: 김승철, 버그

#254 216 be feat 우편번호 수신 데이터 region 구현
  server/src/main/java/backend/section6mainproject/walklog/dto/WalkLogControllerDTO.java
  server/src/main/java/backend/section6mainproject/walklog/dto/WalkLogServiceDTO.java
  server/src/main/java/backend/section6mainproject/walklog/entity/WalkLog.java
  server/src/main/java/backend/section6mainproject/walklog/mapper/WalkLogMapper.java
  server/src/test/java/backend/section6mainproject/walklog/WalkLogStubData.java
  server/src/test/java/backend/section6mainproject/walklog/controller/WalkLogControllerTest.java
  server/src/test/java/backend/section6mainproject/walklog/repository/WalkLogRepositoryTest.java
  server/src/test/java/backend/section6mainproject/walklog/service/WalkLogServiceImplTest.java
Labels: 김성수, 기능

#264 256 be fix 쿠키 조회 안되는 문제 수정
  server/src/main/java/backend/section6mainproject/auth/handler/MemberAuthenticationSuccessHandler.java
Labels: 김승철, 버그

#260 [FE] Design: 작성자 외 유저가 걷기 기록 조회시 작성자 조회 (#252)
  client/src/components/HistoryDetail/Title.module.scss
  client/src/components/HistoryDetail/Title.tsx
  client/src/pages/HistoryDetail.tsx
Labels: 박설화, 디자인

#263 [FE] Fix: 배포 시 발생하는 버그 수정
  client/src/apis/user.ts
  client/src/components/MyPage/EditProfile.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/SignIn.tsx
  client/src/pages/SignUp.tsx
Labels: 하종승, 버그

#268 Chore: 멤버수정시-introduction-추가-안하면-에러나는-버그-수정 (#267)
  server/src/main/java/backend/section6mainproject/member/dto/MemberControllerDTO.java
  server/src/main/java/backend/section6mainproject/member/dto/MemberServiceDTO.java
Labels: 이재환, 버그

#272 256 be fix 쿠키 조회 안되는 문제 수정
  server/src/main/java/backend/section6mainproject/auth/SecurityConfiguration.java
Labels: 김승철, 버그

#275 255 be test 추가되지 않은 테스트 코드전부 작성
  server/src/main/java/backend/section6mainproject/walklog/service/WalkLogServiceImpl.java
  server/src/test/java/backend/section6mainproject/content/WalkLogContentStubData.java
  server/src/test/java/backend/section6mainproject/content/controller/WalkLogContentControllerTest.java
  server/src/test/java/backend/section6mainproject/content/service/WalkLogContentServiceTest.java
  server/src/test/java/backend/section6mainproject/coordinate/socket/CoordinateSocketConnectionTest.java
  server/src/test/java/backend/section6mainproject/member/MemberStubData.java
  server/src/test/java/backend/section6mainproject/member/controller/MemberControllerTest.java
  server/src/test/java/backend/section6mainproject/member/service/MemberServiceTest.java
  server/src/test/java/backend/section6mainproject/walklog/WalkLogStubData.java
  server/src/test/java/backend/section6mainproject/walklog/controller/WalkLogControllerTest.java
  server/src/test/java/backend/section6mainproject/walklog/service/WalkLogServiceImplTest.java
Labels: 김성수, 리팩토링, 테스트

#278 [FE] Feat: OnWalk 페이지 순간기록 수정/삭제
  client/src/apis/snap.ts
  client/src/components/common/ImgInput.tsx
  client/src/components/common/Item/SnapItem.tsx
  client/src/components/common/Modal.module.scss
  client/src/components/common/Modal.tsx
  client/src/components/common/SnapForm.module.scss
  client/src/components/common/SnapForm.tsx
  client/src/pages/OnWalk.module.scss
  client/src/pages/OnWalk.tsx
Labels: 허상범, 기능

#281 [FE] Fix: 버그 수정
  client/index.html
  client/public/manifest.json
  client/src/apis/instance.ts
  client/src/components/ChangePassword/PasswordChanged.tsx
  client/src/components/HistoryList/Toggle.module.scss
  client/src/components/HistoryList/Toggle.tsx
  client/src/components/common/Header.tsx
  client/src/pages/ChangePassword.tsx
  client/src/pages/Feed.module.scss
  client/src/pages/FindPassword.tsx
  client/src/pages/HistoryDetail.module.scss
  client/src/pages/HistoryDetail.tsx
  client/src/pages/HistoryList.module.scss
  client/src/pages/HistoryList.tsx
  client/src/pages/SignIn.tsx
  client/src/pages/SignUp.tsx
  client/src/styles/_reset.scss
  client/src/utils/date-fns.ts
  client/src/utils/date.ts
Labels: 하종승, 버그

#288 [BE] 로그아웃 핸들러 추가
  server/src/main/java/backend/section6mainproject/auth/SecurityConfiguration.java
  server/src/main/java/backend/section6mainproject/auth/handler/RefreshDeleteHandler.java
Labels: 김승철, 버그

#279 Setting: p6spy 라이브러리 설정 추가 (#277)
  server/build.gradle
  server/src/main/java/backend/section6mainproject/P6SpySqlFormatter.java
  server/src/main/resources/application-local.yml
  server/src/main/resources/application-server.yml
Labels: 김성수, 설정

#285 [FE] Design: 탭 바 safe area 테스트 (#284)
  client/src/components/common/Tapbar.module.scss
Labels: 하종승, 테스트, 디자인

#292 291 be fix 회원 가입 오류 수정
  server/src/main/java/backend/section6mainproject/member/repository/MemberRepository.java
Labels: 김승철, 버그

#293 [FE] Fix: history detail loading 화면에 최신 헤더 반영
  client/src/components/HistoryList/Calendar/Calendar.tsx
  client/src/pages/SignUp.tsx
  client/src/pages/loadingPage/CalendarLoading.tsx
  client/src/pages/loadingPage/HistoryDetailLoading.tsx
Labels: 박설화, 버그

#297 [FE] Design: 탭바 safe area 아이폰 status bar
  client/index.html
  client/src/components/common/Tapbar.module.scss
Labels: 하종승, 디자인

#298 [BE] 프로파일 응답에 기록중인 걷기 번호 추가
  server/src/main/java/backend/section6mainproject/auth/AuthMapper.java
  server/src/main/java/backend/section6mainproject/auth/controller/AuthController.java
  server/src/main/java/backend/section6mainproject/auth/dto/ProfileControllerDTO.java
  server/src/main/java/backend/section6mainproject/member/dto/MemberServiceDTO.java
  server/src/main/java/backend/section6mainproject/member/service/MemberServiceImpl.java
  server/src/test/java/backend/section6mainproject/member/MemberStubData.java
  server/src/test/java/backend/section6mainproject/member/controller/MemberControllerTest.java
Labels: 김승철, 기능

#301 [FE] Test: 홈 바 safe area 테스트
  client/index.html
  client/src/components/common/Tapbar.module.scss
  client/src/components/common/Tapbar.tsx
Labels: 하종승, 테스트, 디자인

#304 [FE] Test: 홈 바 safe-area test
  client/src/components/common/Tapbar.module.scss
  client/src/components/common/Tapbar.tsx
Labels: 하종승, 테스트

#306 [FE] Test: 홈 바 safe-area-test
  client/src/components/common/Tapbar.module.scss
Labels: 하종승, 테스트

#308 [FE] Design: safe area에 따라 바뀌어야 할 디자인 변경
  client/src/pages/Feed.module.scss
  client/src/pages/HistoryDetail.module.scss
  client/src/pages/HistoryList.module.scss
  client/src/pages/Home.module.scss
Labels: 하종승, 디자인

#313 [FE] Design: 탭바 요소 가운데 정렬
  client/src/components/common/Tapbar.module.scss
  client/src/components/common/Tapbar.tsx
Labels: 하종승, 디자인

#316 [FE] Feat: 기록탭에 헤더 추가 및 관련 css 추가
  client/src/components/HistoryList/Toggle.module.scss
  client/src/components/header/HomeHeader.module.scss
  client/src/pages/Feed.module.scss
  client/src/pages/HistoryDetail.module.scss
  client/src/pages/HistoryList.module.scss
  client/src/pages/HistoryList.tsx
  client/src/pages/MyPage.module.scss
Labels: 허상범, 기능

#320 [FE] Feat: 회원 탈퇴 안내문 구현
  client/src/components/MyPage/UnregisterInfo.module.scss
  client/src/components/MyPage/UnregisterInfo.tsx
  client/src/components/common/Modal.tsx
Labels: 하종승, 기능

#329 Fix: vercel 배포 에러 (#328)
  client/src/components/HistoryList/Calendar/Calendar.module.scss
  client/src/pages/HistoryList.tsx
  client/vercel.json
Labels: 박설화, 버그

#336 299 be test 인증 관련 테스트
  server/src/main/java/backend/section6mainproject/auth/SecurityConfiguration.java
  server/src/main/java/backend/section6mainproject/auth/controller/AuthController.java
  server/src/main/java/backend/section6mainproject/auth/dto/LoginDTO.java
  server/src/main/java/backend/section6mainproject/auth/dto/ProfileControllerDTO.java
  server/src/test/java/backend/section6mainproject/auth/AuthTest.java
Labels: 김승철, 기능, 테스트

#330 Feat: 멤버 관련 버그 수정 (#325)
  server/src/main/java/backend/section6mainproject/helper/event/PasswordResetEventListner.java
  server/src/main/java/backend/section6mainproject/member/dto/MemberControllerDTO.java
  server/src/main/java/backend/section6mainproject/member/entity/Member.java
Labels: 이재환, 기능, 버그, 설정

#338 Feat: 회원탈퇴시 기존 닉네임 점유권 상실 구현 및 del + 숫자 패턴의 닉네임 block (#331)
  server/src/main/java/backend/section6mainproject/member/dto/MemberControllerDTO.java
  server/src/main/java/backend/section6mainproject/member/entity/Member.java
Labels: 이재환, 기능, 설정

#345 [FE] 구글맵 보기옵션 추가 및 오류 수정
  client/index.html
  client/src/App.tsx
  client/src/assets/sprite-icon.svg
  client/src/components/common/Icon.tsx
  client/src/components/common/Map/MapButton.module.scss
  client/src/components/common/Map/MapButton.tsx
  client/src/components/common/Map/MapCanvas.module.scss
  client/src/components/common/Map/MapCanvas.tsx
  client/src/components/header/HomeHeader.module.scss
  client/src/components/header/HomeHeader.tsx
  client/src/hooks/index.ts
  client/src/hooks/useMarker.ts
  client/src/pages/Home.tsx
Labels: 허상범, 기능, 리팩토링

#347 [FE] Design: 탭바 아이콘 설정
  client/src/assets/sprite-icon.svg
  client/src/components/common/Icon.tsx
  client/src/components/common/Tapbar.tsx
Labels: 허상범, 디자인

#344 Fix: 웹소켓 인증 방식 변경 (#341)
  server/src/main/java/backend/section6mainproject/auth/SecurityConfiguration.java
  server/src/main/java/backend/section6mainproject/coordinate/WebSocketBrokerConfig.java
  server/src/main/java/backend/section6mainproject/coordinate/interceptor/ConnectInterceptor.java
  server/src/main/java/backend/section6mainproject/coordinate/interceptor/ConnectionInterceptor.java
  server/src/test/java/backend/section6mainproject/coordinate/controller/CoordinateControllerTest.java
  server/src/test/java/backend/section6mainproject/coordinate/socket/CoordinateSocketConnectionTest.java
  server/src/test/java/backend/section6mainproject/coordinate/socket/CoordinateSubscribeWrongDestTest.java
Labels: 김승철, 기능

#343 Feat: 회원탈퇴시 WYWdel + 숫자 패턴의 닉네임으로 변경 및 회원탈퇴시점 90일 경과 후 자동삭제 로직 구현 (#331)
  server/src/main/java/backend/section6mainproject/Section6MainProjectApplication.java
  server/src/main/java/backend/section6mainproject/member/dto/MemberControllerDTO.java
  server/src/main/java/backend/section6mainproject/member/entity/Member.java
  server/src/main/java/backend/section6mainproject/member/repository/MemberRepository.java
  server/src/main/java/backend/section6mainproject/member/service/MemberServiceImpl.java
Labels: 이재환, 기능

#352 [FE] Design: favicon 및 앱 아이콘 테스트
  client/index.html
  client/public/icons/favicon.png
  client/public/icons/icon_no_bg.png
  client/public/icons/icon_with_bg.png
  client/public/icons/logo-512.png
  client/public/manifest.json
Labels: 하종승, 디자인

#335 [FE] Design: 이미지 없는 순간 기록 noimage 아이콘 넣기
  client/src/components/Feed/SnapItem.module.scss
  client/src/components/Feed/SnapItem.tsx
  client/src/pages/HistoryDetail.tsx
  client/src/pages/HistoryList.tsx
Labels: 박설화, 디자인

#350 [FE] Feat: 입력된 공백, 띄어쓰기 살려서 보여주기
  client/src/components/HistoryDetail/DetailItem.tsx
  client/src/pages/HistoryList.module.scss
Labels: 박설화, 기능

#334 [FE] Feat: 이미지 파일이 4mb 이상일 경우 alert
  client/src/components/MyPage/ProfileImgInput.tsx
  client/src/components/OnWalk/ImgInput.tsx
  client/src/components/common/ImgInput.tsx
Labels: 하종승, 기능

#358 Fix: 웹소켓 인증 오류 수정 (#357)
  server/src/main/java/backend/section6mainproject/coordinate/interceptor/ConnectInterceptor.java
  server/src/test/java/backend/section6mainproject/coordinate/controller/CoordinateControllerTest.java
  server/src/test/java/backend/section6mainproject/coordinate/socket/CoordinateSocketConnectionTest.java
  server/src/test/java/backend/section6mainproject/coordinate/socket/CoordinateSubscribeWrongDestTest.java
Labels: 김승철, 버그

#369 [BE] 이미지 썸네일 저장 기능 구현
  server/src/main/java/backend/section6mainproject/content/mapper/WalkLogContentMapper.java
  server/src/main/java/backend/section6mainproject/content/service/WalkLogContentServiceImpl.java
  server/src/main/java/backend/section6mainproject/coordinate/interceptor/ConnectionInterceptor.java
  server/src/main/java/backend/section6mainproject/helper/image/AWSS3StorageService.java
  server/src/main/java/backend/section6mainproject/helper/image/StorageService.java
  server/src/main/java/backend/section6mainproject/member/mapper/MemberMapper.java
  server/src/main/java/backend/section6mainproject/member/service/MemberServiceImpl.java
  server/src/main/java/backend/section6mainproject/walklog/mapper/WalkLogMapper.java
  server/src/main/java/backend/section6mainproject/walklog/service/WalkLogServiceImpl.java
  server/src/main/resources/application-local.yml
  server/src/main/resources/application-server.yml
  server/src/test/java/backend/section6mainproject/content/service/WalkLogContentServiceTest.java
  server/src/test/java/backend/section6mainproject/member/service/MemberServiceTest.java
  server/src/test/java/backend/section6mainproject/walklog/service/WalkLogServiceImplTest.java
Labels: 김승철, 기능

#370 [FE] Refactor: axios interceptors로 토큰리프레시 & localStorage로 엑세스토큰 관리 & authAtom 통합
  client/src/apis/instance.ts
  client/src/apis/user.ts
  client/src/components/ChangePassword/PasswordChanged.tsx
  client/src/components/HistoryDetail/DetailItem.tsx
  client/src/components/HistoryDetail/Title.tsx
  client/src/components/HistoryList/Calendar/Calendar.tsx
  client/src/components/MyPage/EditProfile.tsx
  client/src/components/header/HomeHeader.tsx
  client/src/components/header/OnWalkHeader.tsx
  client/src/components/header/WalkHeader.tsx
  client/src/layout/GeneralLayout.tsx
  client/src/pages/AfterWalk.tsx
  client/src/pages/ChangePassword.tsx
  client/src/pages/HistoryDetail.tsx
  client/src/pages/HistoryList.tsx
  client/src/pages/Home.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/SignIn.tsx
  client/src/store/authAtom.ts
  client/src/utils/accessTokenHandler.ts
Labels: 허상범, 기능, 리팩토링

#371 [FE] feat 최초 랜딩 페이지 구현
  client/src/App.tsx
  client/src/pages/Landing.module.scss
  client/src/pages/Landing.tsx
  client/src/router/routerData.tsx
Labels: 하종승, 기능

#375 [FE] Feat: 사진 최대 용량 변경
  client/src/components/MyPage/ProfileImgInput.tsx
  client/src/components/OnWalk/ImgInput.tsx
  client/src/components/common/ImgInput.tsx
Labels: 하종승, 기능

#378 [FE] Feat: 피드의 기록 상세페이지 로그인 없이 접근 가능하게 변경 & 디자인 추가
  client/src/components/Feed/FeedItem.module.scss
  client/src/components/Feed/FeedItem.tsx
  client/src/components/Feed/SnapItem.module.scss
  client/src/components/HistoryList/History.module.scss
  client/src/components/HistoryList/History.tsx
  client/src/components/header/HomeHeader.tsx
  client/src/pages/Feed.tsx
  client/src/pages/HistoryList.module.scss
  client/src/router/routerData.tsx
Labels: 허상범, 기능, 디자인

#380 [FE] 마이페이지, 기록리스트페이지 접근 시 redirect하지않고 자체적으로 콘텐츠 보여주기
  client/src/components/common/Header.module.scss
  client/src/layout/GeneralLayout.tsx
  client/src/pages/HistoryList.tsx
  client/src/pages/MyPage.module.scss
  client/src/pages/MyPage.tsx
  client/src/pages/SignIn.tsx
  client/src/pages/SignUp.tsx
  client/src/pages/loadingPage/MyPageLoading.tsx
  client/src/router/routerData.tsx
Labels: 허상범, 기능, 리팩토링, 디자인

#373 [FE] Feat: 걷기 시작 시 나오는 로딩 화면 구현
  client/src/App.tsx
  client/src/components/common/Landing.module.scss
  client/src/components/common/Landing.tsx
  client/src/components/common/Timer.tsx
  client/src/pages/Landing.tsx
  client/src/pages/OnWalk.tsx
  client/src/pages/loadingPage/Spinner.tsx
Labels: 하종승, 기능

#377 [FE] Feat: pwa 사용법 팝업창 만들기
  client/src/components/Home/PwaCarousel.module.scss
  client/src/components/Home/PwaCarousel.tsx
  client/src/pages/Home.tsx
  client/src/types/Carousel.ts
  client/src/utils/date-fns.ts
Labels: 박설화, 기능

#383 Fix: SockJS 설정 추가 (#381)
  server/src/main/java/backend/section6mainproject/coordinate/WebSocketBrokerConfig.java
  server/src/test/java/backend/section6mainproject/coordinate/controller/CoordinateControllerTest.java
  server/src/test/java/backend/section6mainproject/coordinate/socket/CoordinateSocketConnectionTest.java
  server/src/test/java/backend/section6mainproject/coordinate/socket/CoordinateSubscribeWrongDestTest.java
Labels: 김승철, 리팩토링, 버그

#385 Fix: 웹소켓 오리진 설정 변경 (#384)
  server/src/main/java/backend/section6mainproject/coordinate/WebSocketBrokerConfig.java
Labels: 김승철, 버그

#387 384 be fix 웹소켓 오리진 설정 변경
  server/src/main/java/backend/section6mainproject/coordinate/WebSocketBrokerConfig.java
Labels: 김승철, 버그

#390 [FE] Refactor pwa 안내 팝업창 리팩토링
  client/src/assets/pwa-android-1.png
  client/src/assets/pwa-android-2.png
  client/src/assets/pwa-android-3.png
  client/src/assets/pwa-ios-1.png
  client/src/assets/pwa-ios-2.png
  client/src/assets/pwa-ios-3.png
  client/src/assets/sprite-icon.svg
  client/src/components/Home/PwaCarousel.module.scss
  client/src/components/Home/PwaCarousel.tsx
  client/src/pages/Home.tsx
  client/src/types/Carousel.ts
Labels: 박설화, 리팩토링, 디자인

#392 [FE] Feat: 실시간 좌표 웹소켓으로 서버 전송
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/components/common/Map/StaticPathMap.tsx
  client/src/pages/AfterWalk.module.scss
  client/src/pages/AfterWalk.tsx
  client/src/pages/HistoryDetail.tsx
  client/src/pages/OnWalk.tsx
Labels: 허상범, 기능

#395 [FE] Design: 가로 작은 화면에서도 대응 되도록 min-width 지정
  client/src/components/Home/PwaCarousel.module.scss
Labels: 박설화, 디자인
